Revert "[nrf fromlist] tools: tfm_parse_manifest_list: Fix undefined reference to SLIH API"
This reverts commit 51fb00a7d167d011b3452d0d007c35bb7ba48316.

Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>