[nrf fromlist] tools: tfm_parse_manifest_list: Fix undefined reference to SLIH API
Fix undefined reference to SLIP API e.g. psa_eoi when creating a
partition that listens to multiple interrupt sources using both FLIH and
SLIH interrupt handling.
Since the FLIH interrupt count is more than 1 the SLIH API is excluded
due to the elif check.

Upstream PR:
https://review.trustedfirmware.org/c/TF-M/trusted-firmware-m/+/15470

Change-Id: I23b7a699449963d3d43e45b06f223c4d7b172431
Signed-off-by: Joakim Andersson <joakim.andersson@nordicsemi.no>
(cherry picked from commit 6d1b11c2738acc034f61a50ddb08fc09fb957aa2)